# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
eventCalendar = ->
  $('#calendar').fullCalendar {}

clearCalendar = ->
  $('#calendar').fullCalendar 'delete'
  $('#calendar').html ''
  return


$(document).on 'turbolinks:load', ->
  eventCalendar()
  return
$(document).on 'turbolinks:before-cache', clearCalendar

# ---
# generated by js2coffee 2.2.0
# ---
# generated by js2coffee 2.2.0