# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).ready ->
  $('#calendar').fullCalendar 
    events: '/events.json'
 
 
    console.log('Hi')
    
    error: ->
      alert 'error'
      return
    success: ->
      console.log 'successfully loaded'
      return
  return

# ---
# generated by js2coffee 2.2.0